// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/envoy/tcp/forward_downstream_sni/config.proto

#include "src/envoy/tcp/forward_downstream_sni/config.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace io {
namespace istio {
namespace tcp {
namespace forward_downstream_sni {
namespace v1 {
class ConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Config> _instance;
} _Config_default_instance_;
}  // namespace v1
}  // namespace forward_downstream_sni
}  // namespace tcp
}  // namespace istio
}  // namespace io
static void InitDefaultsscc_info_Config_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::io::istio::tcp::forward_downstream_sni::v1::_Config_default_instance_;
    new (ptr) ::io::istio::tcp::forward_downstream_sni::v1::Config();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::io::istio::tcp::forward_downstream_sni::v1::Config::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Config_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Config_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::io::istio::tcp::forward_downstream_sni::v1::Config, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::io::istio::tcp::forward_downstream_sni::v1::Config)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::io::istio::tcp::forward_downstream_sni::v1::_Config_default_instance_),
};

const char descriptor_table_protodef_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n1src/envoy/tcp/forward_downstream_sni/c"
  "onfig.proto\022&io.istio.tcp.forward_downst"
  "ream_sni.v1\"\010\n\006Configb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_sccs[1] = {
  &scc_info_Config_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_once;
static bool descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto = {
  &descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_initialized, descriptor_table_protodef_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto, "src/envoy/tcp/forward_downstream_sni/config.proto", 109,
  &descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_once, descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_sccs, descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto::offsets,
  file_level_metadata_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto, 1, file_level_enum_descriptors_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto, file_level_service_descriptors_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto), true);
namespace io {
namespace istio {
namespace tcp {
namespace forward_downstream_sni {
namespace v1 {

// ===================================================================

void Config::InitAsDefaultInstance() {
}
class Config::_Internal {
 public:
};

Config::Config()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:io.istio.tcp.forward_downstream_sni.v1.Config)
}
Config::Config(const Config& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:io.istio.tcp.forward_downstream_sni.v1.Config)
}

void Config::SharedCtor() {
}

Config::~Config() {
  // @@protoc_insertion_point(destructor:io.istio.tcp.forward_downstream_sni.v1.Config)
  SharedDtor();
}

void Config::SharedDtor() {
}

void Config::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Config& Config::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Config_src_2fenvoy_2ftcp_2fforward_5fdownstream_5fsni_2fconfig_2eproto.base);
  return *internal_default_instance();
}


void Config::Clear() {
// @@protoc_insertion_point(message_clear_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

const char* Config::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Config::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:io.istio.tcp.forward_downstream_sni.v1.Config)
  return target;
}

size_t Config::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Config::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  GOOGLE_DCHECK_NE(&from, this);
  const Config* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Config>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:io.istio.tcp.forward_downstream_sni.v1.Config)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:io.istio.tcp.forward_downstream_sni.v1.Config)
    MergeFrom(*source);
  }
}

void Config::MergeFrom(const Config& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Config::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Config::CopyFrom(const Config& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:io.istio.tcp.forward_downstream_sni.v1.Config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Config::IsInitialized() const {
  return true;
}

void Config::InternalSwap(Config* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Config::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace forward_downstream_sni
}  // namespace tcp
}  // namespace istio
}  // namespace io
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::io::istio::tcp::forward_downstream_sni::v1::Config* Arena::CreateMaybeMessage< ::io::istio::tcp::forward_downstream_sni::v1::Config >(Arena* arena) {
  return Arena::CreateInternal< ::io::istio::tcp::forward_downstream_sni::v1::Config >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
